# Generated by Django 5.0.2 on 2026-05-25 12:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='auth_provider',
            field=models.CharField(choices=[('direct', 'Direct'), ('google', 'Google')], default='direct', max_length=20),
        ),
    ]
